/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.springframework:spring-webmvc:6.2.2")
    implementation("org.springframework:spring-context:6.2.2")
    implementation("org.springframework:spring-web:6.2.2")
    implementation("org.springframework:spring-orm:6.2.2")
    implementation("org.springframework.data:spring-data-jpa:3.4.2")

    implementation("org.hibernate.orm:hibernate-core:6.6.5.Final")
    implementation("com.zaxxer:HikariCP:5.1.0")
    implementation("com.h2database:h2:2.2.224")

    implementation("org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")

    implementation("jakarta.persistence:jakarta.persistence-api:3.2.0")
    implementation("jakarta.transaction:jakarta.transaction-api:2.0.1")

    compileOnly("jakarta.servlet:jakarta.servlet-api:6.1.0")

    implementation("ch.qos.logback:logback-classic:1.5.6")

    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

